name: condition-monitoring-app
base: core20
version: "1.3.0"
summary: IoT Machine Condition Monitoring App
description: |
    This app includes several IoT softwares bundled as a single snap.
    NodeRED, InfluxDB and Grafana all together and pre-configured, ready to use together
    with the whole ctrlX Automation ecosystem.

grade: stable
confinement: strict

architectures:
    - build-on: amd64
    - build-on: arm64

slots:
    package-assets:
        interface: content
        content: package-assets
        source:
            read:
                - $SNAP/package-assets/condition-monitoring-app

plugs:
    active-solution:
        interface: content
        content: solutions
        target: $SNAP_COMMON/solutions

    datalayer:
        interface: content
        content: datalayer
        target: $SNAP_DATA/.datalayer

hooks:
    connect-plug-active-solution:
        plugs: [active-solution]

apps:
    influx:
        command: bin/influx
        plugs:
            - network
            - home
        slots:
            - package-assets

    influxd:
        command: bin/start-influxd
        daemon: simple
        restart-condition: always
        restart-delay: 15s
        plugs:
            - network
            - network-bind
            - active-solution
        slots:
            - package-assets

    grafana-server:
        command: bin/grafana-server --config $SNAP_DATA/grafana/conf/defaults.ini --homepath $SNAP
        daemon: simple
        restart-condition: on-failure
        restart-delay: 5s
        plugs: [network-bind, network]

    node-red:
        command: bin/start-node-red
        daemon: simple
        restart-condition: always
        restart-delay: 15s
        plugs:
            - audio-playback
            - bluez
            - bluetooth-control
            - camera
            - network-bind
            - network
            - network-observe
            - pulseaudio
            - serial-port
            - removable-media
            - active-solution
        slots:
            - package-assets

parts:
    dependencies:
        plugin: nil
        stage-snaps:
            - influxdb-ijohnson/latest/stable
            - node-red/latest/stable
            - on amd64: [grafana/latest/stable]
            - on arm64: [grafana/latest/beta]
        override-prime: |
            npm install node-red-contrib-influxdb node-red-contrib-ctrlx-automation node-red-dashboard node-red-contrib-opcua
            snapcraftctl prime

    dump-config:
        plugin: dump
        source: ./config
        organize:
            "*": config/

    dump-scripts:
        plugin: dump
        source: ./scripts
        organize:
            "*": bin/

    package-assets:
        plugin: dump
        source: ./package-assets
        organize:
            "*": package-assets/
