name: condition-monitoring-app
base: core20
version: "1.3.0"
summary: IoT Machine Condition Monitoring App
description: |
    This app includes several IoT softwares bundled as a single snap.
    NodeRED, InfluxDB and Grafana all together and pre-configured, ready to use together
    with the whole ctrlX Automation ecosystem.

grade: stable
confinement: strict

architectures:
    - build-on: amd64
    - build-on: arm64

slots:
    package-assets:
        interface: content
        content: package-assets
        source:
            read:
                - $SNAP/package-assets/condition-monitoring-app

plugs:
    active-solution:
        interface: content
        content: solutions
        target: $SNAP_COMMON/solutions

    datalayer:
        interface: content
        content: datalayer
        target: $SNAP_DATA/.datalayer

hooks:
    connect-plug-active-solution:
        plugs: [active-solution]
    influx:
        command: bin/influx
        plugs: [network, home]

    influxd:
        command: bin/influxd --config $SNAP_DATA/influxdb/conf/influxdb.conf
        daemon: simple
        restart-condition: on-failure
        restart-delay: 5s
        plugs: [network-bind, network]

    grafana-server:
        command: bin/grafana-server --config $SNAP_DATA/grafana/conf/defaults.ini --homepath $SNAP
        daemon: simple
        restart-condition: on-failure
        restart-delay: 5s
        plugs: [network-bind, network]

    node-red:
        command: bin/startNR
        daemon: simple
        restart-condition: on-failure
        restart-delay: 5s
        plugs:
            - bluez
            - bluetooth-control
            - home
            - network-bind
            - network
            - network-observe

parts:
    dependencies:
        plugin: nil
        stage-snaps:
            - influxdb-ijohnson/latest/stable
            - node-red/latest/stable
            - on amd64: [grafana/latest/stable]
            - on arm64: [grafana/latest/beta]
        override-prime: |
            npm install node-red-contrib-influxdb node-red-contrib-ctrlx-automation node-red-dashboard node-red-contrib-opcua
            snapcraftctl prime

    grafana-config:
        plugin: dump
        source: ./grafana
        organize: 
            "*" : dump/

    influx-config:
        plugin: dump
        source: ./influxd
        organize: 
            "*": dump/

    package-assets:
        plugin: dump
        source: ./package-assets
        organize:
            "*": package-assets/ 