name: condition-monitoring-app
base: core20
version: "1.3.0"
summary: IoT Machine Condition Monitoring App
description: |
    This app includes several IoT softwares bundled as a single snap.
    NodeRED, InfluxDB and Grafana all together and pre-configured, ready to use together
    with the whole ctrlX Automation ecosystem.

grade: stable
confinement: strict

architectures:
    - build-on: amd64
    - build-on: arm64

slots:
    package-assets:
        interface: content
        content: package-assets
        source:
            read:
                - $SNAP/package-assets/condition-monitoring-app

plugs:
    active-solution:
        interface: content
        content: solutions
        target: $SNAP_COMMON/solutions

    datalayer:
        interface: content
        content: datalayer
        target: $SNAP_DATA/.datalayer

hooks:
    connect-plug-active-solution:
        plugs: [active-solution]

apps:
    influx:
        command: usr/bin/influx
        plugs:
            - network
            - home
        slots:
            - package-assets

    influxd:
        command: bin/start-influxd
        daemon: simple
        restart-condition: always
        restart-delay: 15s
        plugs:
            - network
            - network-bind
            - active-solution
        slots:
            - package-assets

    grafana-server:
        command: bin/start-grafana
        daemon: simple
        restart-condition: always
        restart-delay: 15s
        plugs:
            - network
            - network-bind
            - active-solution
        slots:
            - package-assets

    node-red:
        command: bin/start-node-red
        daemon: simple
        restart-condition: always
        restart-delay: 15s
        plugs:
            - audio-playback
            - bluez
            - bluetooth-control
            - camera
            - network-bind
            - network
            - network-observe
            - pulseaudio
            - serial-port
            - removable-media
            - active-solution
        slots:
            - package-assets

parts:
    node-red:
        plugin: nil
        stage-snaps:
            - node-red/latest/stable
        override-prime: |
            npm install node-red-dashboard 
            npm install node-red-contrib-influxdb 
            npm install node-red-contrib-ctrlx-automation
            npm install node-red-contrib-modbus
            npm install node-red-debugger

            npm install nrlint
            mkdir -p $SNAPCRAFT_PRIME/lib
            npx nrlint --init > $SNAPCRAFT_PRIME/lib/.nrlintrc.js

            snapcraftctl prime

    influxdb:
        plugin: dump
        source:
         - on amd64: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
         - on arm64: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_arm64.deb

    grafana:
        plugin: dump
        source:
        - on amd64: https://dl.grafana.com/oss/release/grafana_9.2.2_amd64.deb
        - on arm64: https://dl.grafana.com/oss/release/grafana_9.2.2_arm64.deb

    dump-config:
        plugin: dump
        source: ./config
        organize:
            "*": config/

    dump-scripts:
        plugin: dump
        source: ./scripts
        organize:
            "*": bin/

    package-assets:
        plugin: dump
        source: ./package-assets
        organize:
            "*": package-assets/
