on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

name: Build snap files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup snapcraft
        run: sudo snap install snapcraft --classic

      - name: Build amd64 snap
        run: ./build-amd64.sh

      - name: Build arm64 snap
        run: ./build-arm64.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: condition-monitoring-app_*.snap
