#!/bin/sh -e

# Copies Node-RED configuration file 'settings.js' into current 'Active Configuration'

NODERED_DIR=$SNAP_COMMON/solutions/activeConfiguration/condition-monitoring-app/node-red

if [ ! -d "$NODERED_DIR" ]; then 
   echo "Creating directory at $NODERED_DIR"
   mkdir -p $NODERED_DIR
fi

cp $SNAP/config/node-red.conf $NODERED_DIR/settings.js
chmod 666 $NODERED_DIR/settings.js


# Copies InfluxDB configuration file 'influxdb.conf' into current 'Active Configuration'

INFLUXDB_DIR=$SNAP_COMMON/solutions/activeConfiguration/condition-monitoring-app/influxdb

if [ ! -d "$INFLUXDB_DIR" ]; then 
   echo "Creating directory at $INFLUXDB_DIR"
   mkdir -p $INFLUXDB_DIR
fi

cp $SNAP/config/influxdb.conf $INFLUXDB_DIR/influxdb.conf
chmod 666 $INFLUXDB_DIR/influxdb.conf


# Copies Grafana configuration file 'grafana.conf' into current 'Active Configuration'

GRAFANA_DIR=$SNAP_COMMON/solutions/activeConfiguration/condition-monitoring-app/grafana

if [ ! -d "$GRAFANA_DIR" ]; then 
   echo "Creating directory at $GRAFANA_DIR"
   mkdir -p $GRAFANA_DIR
   cp -r $SNAP/usr/share/grafana/ $GRAFANA_DIR/../
fi

cp -f $SNAP/config/grafana.conf $GRAFANA_DIR/conf/defaults.ini
chmod 666 $GRAFANA_DIR/conf/defaults.ini
