#!/bin/sh -e

echo "Install hook triggered"

# Check if directory exists
if [ ! -d "$SNAP_COMMON/influxdb/" ]; then
    echo "Creating directory at $SNAP_COMMON/influxdb/..."
    mkdir -p $SNAP_COMMON/influxdb/conf
    mkdir -p $SNAP_COMMON/influxdb/meta
    mkdir -p $SNAP_COMMON/influxdb/data
    mkdir -p $SNAP_COMMON/influxdb/wal
fi